# Generated by Django 3.2.5 on 2022-01-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nobreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('serial', models.CharField(max_length=100, verbose_name='Serial')),
                ('mark', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('identified', models.CharField(max_length=100, verbose_name='Nº Patrimônio')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('sector', models.CharField(max_length=200, verbose_name='Setor')),
                ('location', models.CharField(max_length=200, verbose_name='Localidade')),
            ],
            options={
                'verbose_name': 'Nobreak',
                'verbose_name_plural': 'Nobreaks',
                'ordering': ['model', 'sector'],
            },
        ),
    ]
