# Generated by Django 3.2.5 on 2022-01-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('hostname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Computador')),
                ('ip', models.CharField(blank=True, max_length=12, null=True, verbose_name='IP')),
                ('mac', models.CharField(blank=True, max_length=18, null=True, verbose_name='MAC')),
                ('mark', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Serial')),
                ('identified', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nª Patrimônio')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('sector', models.CharField(blank=True, max_length=200, null=True, verbose_name='Setor')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Localidade')),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
                'ordering': ['mark', 'sector'],
            },
        ),
    ]
