# Generated by Django 3.2.5 on 2022-01-29 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitor',
            options={'ordering': ['mark', 'sector'], 'verbose_name': 'Monitor', 'verbose_name_plural': 'Monitores'},
        ),
    ]
