# Generated by Django 3.2.5 on 2022-01-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitores', '0002_alter_monitor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='identified',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nª Patrimônio'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Localidade'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='sector',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Serial'),
        ),
    ]
